@startuml Use Case Diagram

:Player: as p
:Computer Player: as cp

package Game{
    (Play Turn) as pt
    (Save Game) as sg
    (Load Game) as lg
    (Made Event Decision) as ed
    (New Game) as ng

}


p --> pt
p --> ed
p --> lg
p --> sg
p --> ng

cp --> ed
cp --> pt

pt ..> sg: <<extend>>
ng ..> lg: <<extend>>

@enduml